### PR TITLE
version bump 0.5.10

### PR DESCRIPTION
**Pull request by k-dominik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
-> this gave me a `No changes made. This feedstock is up-to-date.` message. Is that expected?
* [x] Ensured the license file is being packaged.

Please note that the build for this package is currently failing because I pushed a branch (for the previous version bump to `0.5.9`) to the repo by accident, and it go build and uploaded. The one from https://github.com/conda-forge/apistar-feedstock/pull/1 failed then, because the files were already present. Sorry

### CODE REVIEW

**Comment by djsutherland** [comment]
>  Re-rendered with the latest `conda-smithy`
-> this gave me a `No changes made. This feedstock is up-to-date.` message. Is that expected?

Yep, that's fine. It only sometimes changes things.

**Comment by k-dominik** [comment]
thank you for the info @dougalsutherland

**Comment by k-dominik** [comment]
@dougalsutherland : sorry, one last question; is it okay to merge PRs here myself?

**Comment by djsutherland** [comment]
Yes! You're in charge. :)  Feel free to ping (with @) conda-forge/help-python or conda-forge/core if you need help with something, though.

**Comment by k-dominik** [comment]
@dougalsutherland thank you very much for the help :)

Also it's very good to know that the community is around in case of problems

**Pull request merged**
